name: bayesian_conda_env
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=3.2.8
  - aesara=2.3.8
  - arviz=0.5.1
  - pymc3=3.8
  # Without mkl, there will be a warning: No module named 'mkl', but it won't affect running the code.
  # - mkl-service=2.4.0
  - nomkl
  - sunode=0.2.1
  - scikit-learn=1.0.2
  - pygpu=0.7.6
  - google-cloud-bigquery[bqstorage,pandas]>=2.13.1,<3.0.0
  - seaborn>=0.11.1,<1.0.0
  - plotly=5.5.0
  - awscli>=1.22.0,<2.0.0
