name: bayesian_conda_env
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=3.2.8
  - pandas
  - numpy
  - aesara=2.3.8
  - arviz=0.5.1
  - pymc3=3.8
  - mkl-service=2.4.0
  - sunode=0.2.1
  - ipython=8.0.1
  - scikit-learn=1.0.2
  - pygpu=0.7.6
