on: push

name: Tests

jobs:
  runTests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade 'pip<20.3'
        pip install -r covid19-etl-requirements.txt
        pip install -r test-requirements.txt
        pip install pytest~=3.6
    - name: Test with pytest
      run: |
        pytest -vv covid19-etl/tests
